package com.walkwind.spring5.entity;

import java.io.Serializable;

/**
 * null
 * @TableName user
 */
public class User implements Serializable {
    private Integer id;

    /**
     *
     *
     * @mbg.generated 2021-03-16 20:48:50
     */
    private String name;

    /**
     *
     *
     * @mbg.generated 2021-03-16 20:48:50
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated 2021-03-16 20:48:50
     */
    private static final long serialVersionUID = 1L;


    public User() {
    }

    public User(Integer id,String name, Integer age) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }
}