package generate;

import java.io.Serializable;

/**
 * null
 * @TableName user
 */
public class User implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    private String name;

    /**
     * 
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    public String getName() {
        return name;
    }

    /**
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    public Integer getAge() {
        return age;
    }

    /**
     *
     * @mbg.generated 2021-03-16 20:50:43
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}